### ISSUE TITLE
Setup our own Exchange Server for testing (Windows server on AWS)

### ISSUE THREAD

**Issue by mihow** [mihow/footer#1]

**Comment by popmechanic** [comment]
https://www.rackspace.com/en-us/email-hosting/hosted-exchange

**Comment by mihow** [comment]
- I requested the free trial for hosted Exchange at Rackspace. They say they need to verify my account during business hours, so waiting on that. I am skeptical about whether we can configure the email relay with the hosted version. I will submit a support ticket about it if it doesn't look possible in the control panel.

- I registered for a free 180 day license for Microsoft Exchange Server 2013 and downloaded the installer. So we should be able to set it up on any old box with Windows Server. I am going to try this on AWS.

- AWS has a CloudFormation "quick start" template for setting up a cloud stack for Exchange. 
http://docs.aws.amazon.com/quickstart/latest/exchange/welcome.html

- The cost estimate for that one is $5.50 an hour. It's a pretty beefy stack, made for hosting an actual companies email I suppose. It failed to launch with the default settings, rolling that back for the moment.

- I am going to try setting up a single Windows instance on EC2 first, and installing Exchange on that.
    - Use an existing Windows Server AMI, select a hard drive at least 8gb

**Comment by mihow** [comment]
Some notes about setting up an Exchange server for testing. They do note the surprise high bills that you can get from the AWS or Azure stacks and suggest your own box.

http://practical365.com/exchange-server/how-to-build-an-exchange-server-test-environment/

Direct links to download exchange:
http://care.dlservice.microsoft.com/dl/download/8/1/1/811B7C54-DA45-48AF-A912-0AA2B6FDA02C/Exchange-x64.exe
https://www.microsoft.com/en-us/evalcenter/evaluate-exchange-server-2013?i=1

**Comment by popmechanic** [comment]
Hopefully the managed hosted solution will do the trick, but I think it was wise that you've begun looking at plan B. I can probably help by providing some AWS infrastructure if we need it. Let's discuss after you hear from Rackspace. Good work so far.

**Comment by mihow** [comment]
- Exchange 2016 edition
- Windows Server 2012 R2
- AWS EC2 instance

**Comment by mihow** [comment]
This could potentially be outsourced for cheap via upwork.com or fiver.com

**Comment by mihow** [comment]
I realized that Microsoft probably encourages people to setup Exchange on their own Azure cloud platform and whammo:

https://technet.microsoft.com/en-us/library/mt733070(v=exchg.160).aspx

That should be faster to setup than on AWS despite being unfamiliar territory.

**Comment by mihow** [comment]
I also contacted these remote freelancers to see what they say:

https://www.fiverr.com/hussainsheikh/setup-microsoft-exchange-server-2016
https://www.upwork.com/freelancers/~01cc044f2ed6a182e0 ($75)
