### ISSUE TITLE
Job description for dynamic Exchange footer script

### ISSUE THREAD

**Issue by mihow** [mihow/footer#12]
## Create a custom disclaimer/footer that is unique to all outgoing email in Exchange Server.

We need to create a dynamic "disclaimer" in the footer of all outgoing email in Exchange Sever 2016. 

- Each outgoing email needs to contain a footer that contains a UNIQUE_ID variable.
- The UNIQUE_ID value needs to be a URL-safe sequence of numbers or letters that is unique to every email. The ID can be random, sequential or whatever makes it unique.
- The same ID needs to appear multiple times within the same email (see example)
- The footer needs to be in formatted HTML
- Documentation about how to integrate/install the solution into our Exchange Server
- Example email:

```html
Dear Sir,

Message body text here.

Thank you,
Tim

<h1>FOOTER FOLLOWS</h1>
<p>The ID for this email is: {{ UNIQUE_ID }}</p>
<p>Tracking image: <img src="http://example.org/image.jpg?id={{ UNIQUE_ID }}"></p>
<p>Once again, your unique ID is: {{ UNIQUE_ID }}</p>
```

- We are running an on-premise installation of Microsoft Exchange 2016 on Windows Server 2012 R2.
- We have seen something similar done by creating a custom Mail Transport Agent in Visual Basic and adding it to the outgoing Mail Flow. We are open to any strategy that gets the job done.

**Comment by popmechanic** [comment]
This is great. Zero changes needed.

**Comment by mihow** [comment]
Okay post is up! Fingers crossed: https://www.upwork.com/jobs/_~019e0a23cd0d51548a/
