### ISSUE TITLE
Spruce up dynamic image with geolocation

### ISSUE THREAD

**Issue by mihow** [mihow/footer#8]
From: New York, New York
To: Geolocated IP of request

- [x] Add basic geolocation with client's location to dynamic image
- [x] Add "send test email" button from dashboard (right now image gets rendered when you paste before sending)
- [x] Add some sort of logging (Sentry, Google Analytics)

**Comment by mihow** [comment]
[1/18/17, 11:25:51 AM] Marcus Estes: https://www.iplocation.net

**Comment by flintcog** [comment]
https://mapzen.com

**Comment by mihow** [comment]
Here's an article from MailChimp about the caveats of IP geolocation:
http://kb.mailchimp.com/lists/managing-subscribers/about-geolocation

And some good info about how Gmail caches images. If we can get a unique ID in the image tag I think it might get around this:
https://litmus.com/help/analytics/understanding-gmail-opens/

**Comment by mihow** [comment]
Free geoip database: http://dev.maxmind.com/geoip/geoip2/geolite2/ (example service:  http://www.freegeoip.net)
Paid option (more precision): https://www.maxmind.com/en/geoip2-precision-services

**Comment by mihow** [comment]
First stab at adding the clients location in the dynamic image:
https://footer.bunsen.town

**Comment by mihow** [comment]
@flintcog & @popmechanic I added a "Send test email" method so you can try sending the current dynamic image with basic geolocation:
https://footer.bunsen.town/

P.S. I am headed to Breitenbush now and will be out of service until Friday evening!

**Comment by mihow** [comment]
The big snag I ran into is that since 2012 Gmail routes all of their images through a proxy and any emails opened in Gmail appear to be from Mountain View, CA. This is [documented](https://litmus.com/blog/gmail-adds-image-caching-what-you-need-to-know) by email marketers on the web and the only workaround seems to be to get the user's location when they click a tracked link.

One interesting option would be to create a footer that includes some special links from which we can extract better data, like those that marketing emails use for "surveys".

**Example**: 
"You are now a participant in the Whitney Biennial! [Please explain](http://footer.bunsen.town)"


![image](https://cloud.githubusercontent.com/assets/158175/22227306/8dab9b28-e17f-11e6-813e-6584bc9f15ab.png)
From: http://kb.mailchimp.com/campaigns/design/send-a-simple-poll-or-survey-to-subscribers

**Comment by flintcog** [comment]
This is, indeed, a snag! I understand the survey thing--but it's important to me that we implicate the passive receiver. Shoot. Gmail strikes again. There's gotta be a way.

**Comment by popmechanic** [comment]
Here we go. We can just user a no-cache flag in the header to tell gmail not to proxy the image: https://movableink.com/blog/real-time-content-and-re-open-tracking-return-to-gmail/

**Comment by popmechanic** [comment]
More on that solution: http://stackoverflow.com/questions/21802820/dynamic-images-for-email-such-as-countdown-clocks-in-light-of-gmail-image-cachi/40569195#40569195

**Comment by popmechanic** [comment]
Damn, on further investigation it looks like we'll get open requests but not location.
